spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lowi?serverTimezone=GMT%2B8&amp&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    password: 123456
    host: localhost
#    elasticsearch:
#      rest:
#        uris: 10.10.10.162:9200
management:
  endpoint:
    health:
      show-details: always
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.lowi.admin.entity
  global-config:
    db-config:
      capital-mode: true
      column-like: true
mq:
  producerGroup: lowiProducer
  serverAddr: 47.114.180.75:9876

localhostUrl: http://localhost:8122

uploadUrl:  /usr/local/web/img/
fileUrl: http://47.114.180.75/img/

elasticsearchServerUrl: 10.10.10.162
elasticsearchServerPort: 9200